from typing import Any, Dict, Optional, Awaitable
from .modern import ModernTumblrRestClient
from .types import Post

class AsyncModernTumblrRestClient:
    @property
    def sync_client(self) -> ModernTumblrRestClient: ...
    def info(self) -> Awaitable[Dict[str, Any]]: ...
    def posts(self, blogname: str, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def create_post(self, blogname: str, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def edit_post(self, blogname: str, id: Any, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def reblog_post(self, blogname: str, parent_blogname: str, id: Any, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def notifications(self, blogname: str, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def notes(self, blogname: str, id: Any, **kwargs: Any) -> Awaitable[Dict[str, Any]]: ...
    def get_single_post(self, blogname: str, id: Any, **kwargs: Any) -> Awaitable[Optional[Post]]: ...
    def get_root_post(self, post: Post) -> Awaitable[Post]: ...
    def refresh_token(self) -> Awaitable[Dict[str, Any]]: ...
