from typing import Any, Dict, Optional
from .modern import ModernTumblrRestClient

class AsyncModernTumblrRestClient:
    @property
    def sync_client(self) -> ModernTumblrRestClient: ...
    async def info(self) -> Dict[str, Any]: ...
    async def posts(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    async def create_post(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    async def edit_post(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    async def reblog_post(self, blogname: str, parent_blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    async def notifications(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    async def notes(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    async def get_single_post(self, blogname: str, id: Any, **kwargs: Any) -> Optional[Dict[str, Any]]: ...
    async def get_root_post(self, post: Dict[str, Any]) -> Dict[str, Any]: ...
    async def refresh_token(self) -> Dict[str, Any]: ...
