from typing import Any, Dict, Iterator, Mapping, Optional, Sequence
from . import TumblrRestClient

class ModernTumblrRestClient(TumblrRestClient):
    def create_post(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    def edit_post(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def notifications(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    def notes(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def get_single_post(self, blogname: str, id: Any, **kwargs: Any) -> Optional[Dict[str, Any]]: ...
    def reblog_post(self, blogname: str, parent_blogname: str, id: Any, parent_blog_uuid: Optional[str] = ..., reblog_key: Optional[str] = ..., **kwargs: Any) -> Dict[str, Any]: ...
    def iter_posts(self, blogname: str, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Dict[str, Any]]: ...
    def iter_queue(self, blogname: str, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Dict[str, Any]]: ...
    def iter_likes(self, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Dict[str, Any]]: ...
    def get_root_post(self, post: Dict[str, Any]) -> Dict[str, Any]: ...
