from typing import Any, Dict, Iterator, Optional
from . import TumblrRestClient
from .types import Post

class ModernTumblrRestClient(TumblrRestClient):
    consume_in_npf_by_default: bool
    def npf_consumption_on(self) -> None: ...
    def npf_consumption_off(self) -> None: ...
    def create_post(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    def edit_post(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def notifications(self, blogname: str, **kwargs: Any) -> Dict[str, Any]: ...
    def notes(self, blogname: str, id: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def get_single_post(self, blogname: str, id: Any, **kwargs: Any) -> Optional[Post]: ...
    def reblog_post(self, blogname: str, parent_blogname: str, id: Any, parent_blog_uuid: Optional[str] = ..., reblog_key: Optional[str] = ..., **kwargs: Any) -> Dict[str, Any]: ...
    def iter_posts(self, blogname: str, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Post]: ...
    def iter_queue(self, blogname: str, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Post]: ...
    def iter_likes(self, max_items: Optional[int] = ..., **kwargs: Any) -> Iterator[Post]: ...
    def get_root_post(self, post: Post) -> Post: ...
