from typing import Any, Dict, Iterator, Optional, Sequence, Tuple

def text_block(text: str, subtype: Optional[str] = ..., formatting: Optional[Sequence[Dict[str, Any]]] = ...) -> Dict[str, Any]: ...
def link_block(url: str, title: Optional[str] = ..., description: Optional[str] = ..., author: Optional[str] = ..., site_name: Optional[str] = ...) -> Dict[str, Any]: ...
def image_block(url: str, media_type: Optional[str] = ..., width: Optional[int] = ..., height: Optional[int] = ..., alt_text: Optional[str] = ...) -> Dict[str, Any]: ...
def image_upload_block(identifier: str, media_type: str = ..., alt_text: Optional[str] = ...) -> Dict[str, Any]: ...
def iter_blocks(post: Dict[str, Any], include_trail: bool = ...) -> Iterator[Dict[str, Any]]: ...
def iter_media(post: Dict[str, Any], media_types: Optional[Sequence[str]] = ..., include_trail: bool = ...) -> Iterator[Dict[str, Any]]: ...
def iter_images(post: Dict[str, Any], include_trail: bool = ...) -> Iterator[Dict[str, Any]]: ...
def iter_text(post: Dict[str, Any], include_trail: bool = ...) -> Iterator[str]: ...
def root_post_reference(post: Dict[str, Any]) -> Optional[Tuple[str, Any]]: ...
